version: "3.6"
services:
  api:
    image: kc-api-img
    container_name: kc-api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./api
        target: /home/app
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 256m
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    environment:
      - API_PORT=${API_PORT}
      - NODE_ENV=development
  web:
    stdin_open: true
    image: kc-web-img
    container_name: kc-web
    build:
      context: ./web
      dockerfile: Dockerfile.node
    volumes:
      - type: bind
        source: ./web
        target: /home/app
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 256m
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    depends_on:
      - api
    environment:
      - WEB_PORT=${WEB_PORT}
      - NODE_ENV=development
