export const AUTHENTICATION = {
  SUCCESS: 'AUTHENTICATE_SUCCESS',
  FAILED: 'AUTHENTICATE_FAILED',
};

export const GET_IDPS = {
  START: 'GET_IDPS_START',
  SUCCESS: 'GET_IDPS_SUCCESS',
  ERROR: 'GET_IDPS_ERROR',
};

export const NEW_REQUEST = {
  START: 'NEW_REQUEST_START',
  SUCCESS: 'NEW_REQUEST_SUCCESS',
  ERROR: 'NEW_REQUEST_ERROR',
};
