export const AUTHENTICATION = {
  SUCCESS: 'AUTHENTICATE_SUCCESS',
  FAILED: 'AUTHENTICATE_FAILED',
};

export const GET_IDPS = {
  START: 'GET_IDPS_START',
  SUCCESS: 'GET_IDPS_SUCCESS',
  ERROR: 'GET_IDPS_ERROR',
};
