apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: realm-o-matic-api-bc
labels:
  template: realm-o-matic-api
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: ${NAME}-api
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-api${SUFFIX}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-api:${VERSION}
    postCommit: {}
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_CONTEXT_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          namespace: ${SOURCE_IMAGE_NAMESPACE}
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: realm-o-matic
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: SOURCE_REPOSITORY_URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/realm-o-matic.git
- description: SOURCE_REPOSITORY_REF
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: master
- description: SOURCE_CONTEXT_DIR
  displayName: SOURCE_CONTEXT_DIR
  name: SOURCE_CONTEXT_DIR
  required: true
  value: api
- description: The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  value: 'openshift'
  required: true
- description: The name of the source image.
  displayName: Source Image Name
  name: SOURCE_IMAGE_NAME
  value: 'nodejs'
  required: true
- description: The tag of the source image.
  displayName: Source Image Tag
  name: SOURCE_IMAGE_TAG
  value: "10"
  required: true
