apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: realm-o-matic-api-dc
labels:
  template: realm-o-matic-api
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-api${SUFFIX}
    labels:
      app: realm-o-matic
  spec:
    replicas: 3
    selector:
      deploymentconfig: ${NAME}-api${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-api${SUFFIX}
      spec:
        containers:
        - image: ${NAME}-api:${VERSION}
          name: realm-o-matic-api
          ports:
          - containerPort: 8000
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          env:
          - name: API_HOST
            value: ${HOST_VALUE}
          - name: API_PORT
            value: ${API_PORT_VALUE}
          - name: API_SSO_URL
            value: ${API_SSO_URL_VALUE}
          - name: API_SSO_REALM
            value: ${API_SSO_REALM_VALUE}
          - name: API_SSO_CLIENT_ID
            value: ${API_SSO_CLIENT_ID_VALUE}
          - name: API_SSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-sso
                key: API_SSO_CLIENT_SECRET
          - name: GITHUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-gh
                key: GITHUB_TOKEN
          - name: GITHUB_OWNER
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-gh
                key: GITHUB_OWNER
          - name: GITHUB_REPO
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-gh
                key: GITHUB_REPO
          - name: EMAIL_HOST
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-email
                key: EMAIL_HOST
          - name: EMAIL_PORT
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-email
                key: EMAIL_PORT
          - name: EMAIL_SENDER
            valueFrom:
              secretKeyRef:
                name: realmomatic-api-email
                key: EMAIL_SENDER
          - name: REVIEW_EMAIL
            value: ${REVIEW_EMAIL_VALUE}
          - name: ADMIN_EMAIL
            value: ${ADMIN_EMAIL_VALUE}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - realm-o-matic-api
        from:
          kind: ImageStreamTag
          name: ${NAME}-api:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}-api${SUFFIX}
    labels:
      app: realm-o-matic
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: ${NAME}-api${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-api${SUFFIX}
    labels:
      app: realm-o-matic
  spec:
    host: ${HOST_VALUE}
    path: /api
    port:
      targetPort: api
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}-api${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: realm-o-matic
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: The url of the api
  displayName: Realm-o-matic api
  name: HOST_VALUE
  required: false
  value: ''
- description: The port of the api
  displayName: Realm-o-matic api
  name: API_PORT_VALUE
  required: false
  value: ''
- description: The url of the api sso client
  displayName: Realm-o-matic api sso
  name: API_SSO_URL_VALUE
  required: false
  value: ''
- description: The realm of the api sso realm
  displayName: Realm-o-matic api sso
  name: API_SSO_REALM_VALUE
  required: false
  value: ''
- description: The client id of the api sso client
  displayName: Realm-o-matic api sso
  name: API_SSO_CLIENT_ID_VALUE
  required: false
  value: ''
- description: The email address of keycloak realm reviewer
  displayName: Keycloak realm reviewer email
  name: REVIEW_EMAIL_VALUE
  required: false
  value: ''
- description: The email address of keycloak admin
  displayName: Keycloak admin email
  name: ADMIN_EMAIL_VALUE
  required: false
  value: ''
