apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  data:
    Caddyfile: |
      0.0.0.0:2015
      root /var/www/html/build
      log stdout
      errors stdout
      rewrite {
        if  {path} not_match ^\/0.0.0.0
        to  {path} {path}/ /?_url={uri}
      }
      templates {
        ext  .js
      }
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: realm-o-matic-web-caddy
    labels:
      app: realm-o-matic
  type: Opaque
