apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    EMAIL_HOST: ${EMAIL_HOST}
    EMAIL_PORT: ${EMAIL_PORT}
    EMAIL_SENDER: ${EMAIL_SENDER}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: realmomatic-api-email
    labels:
      app: realm-o-matic
  type: Opaque
parameters:
- description: Email server host
  displayName: EMAIL_HOST
  name: EMAIL_HOST
  required: true
  value: ''
- description: Email server port
  displayName: EMAIL_PORT
  name: EMAIL_PORT
  required: true
  value: ''
- description: Sender email address
  displayName: EMAIL_SENDER
  name: EMAIL_SENDER
  required: true
  value: ''
