apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: realm-o-matic-web
labels:
  template: realm-o-matic-web
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}-static
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    replicas: 2
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
    strategy:
      resources:
        requests:
          cpu: '100m'
        limits:
          cpu: '150m'
    template:
      metadata:
        creationTimestamp: null
        labels:
          deploymentconfig: ${NAME}-static${SUFFIX}
      spec:
        containers:
        - image: ${NAME}-static:${VERSION}
          name: realm-o-matic-web
          args:
          - /tmp/scripts/run
          ports:
          - containerPort: 2015
            protocol: TCP
          resources:
            requests:
              cpu: '100m'
            limits:
              cpu: '150m'
          env:
          - name: REACT_APP_SSO_BASE_URL
            value: ${REACT_APP_SSO_BASE_URL_VALUE}
          - name: REACT_APP_SSO_REALM_NAME
            value: ${REACT_APP_SSO_REALM_NAME_VALUE}
          - name: REACT_APP_SSO_CLIENT_ID
            value: ${REACT_APP_SSO_CLIENT_ID_VALUE}
          volumeMounts:
          - name: ${VOLUMN_NAME}
            mountPath: /etc/Caddyfile
            readOnly: true
            subPath: Caddyfile
        volumes:
        - name: ${VOLUMN_NAME}
          configMap:
            defaultMode: 420
            name: ${NAME}-caddy
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - realm-o-matic-web
        from:
          kind: ImageStreamTag
          name: ${NAME}-static:${VERSION}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    ports:
    - name: web
      port: 2015
      protocol: TCP
      targetPort: 2015
    selector:
      deploymentconfig: ${NAME}-static${SUFFIX}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${NAME}-static${SUFFIX}
  spec:
    host: ${HOST_VALUE}
    port:
      targetPort: web
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NAME}-static${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: realm-o-matic-web
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: A name used for routes/services and deployment configs
  displayName: Host
  name: HOST_VALUE
  required: false
  value: ''
- description: A volumn used for the caddy from config map
  displayName: volumn name
  name: VOLUMN_NAME
  required: false
  value: web-caddy-config
- description: The url of the web sso client
  displayName: Realm-o-matic web sso
  name: REACT_APP_SSO_BASE_URL_VALUE
  required: false
  value: ''
- description: The realm of the web sso realm
  displayName: Realm-o-matic web sso
  name: REACT_APP_SSO_REALM_NAME_VALUE
  required: false
  value: ''
- description: The client id of the web sso client
  displayName: Realm-o-matic web sso
  name: REACT_APP_SSO_CLIENT_ID_VALUE
  required: false
  value: ''
