apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: realm-o-matic-web-bc
labels:
  template: realm-o-matic-web
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      shared: true
    name: ${NAME}-web
  spec:
    lookupPolicy:
      local: false
#Final ImageStream created by adding the output of the nodejs build in caddy
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}-web-static
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}-web${SUFFIX}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-web:${VERSION}
    postCommit: {}
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      contextDir: ${SOURCE_CONTEXT_DIR}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}
          namespace: ${SOURCE_IMAGE_NAMESPACE}
      type: Source
    # triggers:
    # - type: ConfigChange
    # - imageChange: {}
    #   type: ImageChange
#Chainned build
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: ${NAME}-web-static${SUFFIX}
    name: ${NAME}-web-static${SUFFIX}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-web-static:${VERSION}
    postCommit: {}
    resources:
      requests:
        cpu: 1
      limits:
        cpu: 2
    source:
      type: Dockerfile
      dockerfile: |-
        FROM image-registry.openshift-image-registry.svc:5000/6d70e7-tools/caddy-s2i-v2:latest
        COPY build /opt/app-root/
        CMD /usr/libexec/s2i/run
      images:
      - from:
          kind: ImageStreamTag
          name: '${NAME}-web:${VERSION}'
        paths:
        - sourcePath: /opt/app-root/src/build/
          destinationDir: "."
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: caddy-s2i-v2:latest
      type: Docker
    # triggers:
    # - imageChange:
    #     from:
    #       kind: ImageStreamTag
    #       name: ${NAME}-web:${VERSION}
    #   type: ImageChange
    # - type: ConfigChange
    # - imageChange: {}
    #   type: ImageChange
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: realm-o-matic
- description: A name suffix used for all objects
  displayName: Suffix
  name: SUFFIX
  required: false
  value: -dev
- description: A version used for the image tags
  displayName: version
  name: VERSION
  required: true
  value: v1.0.0
- description: The openshift project where builds and target images are stored.
  displayName: Build Project
  name: SOURCE_IMAGE_NAMESPACE
  value: 'openshift'
  required: true
- description: The name of the source image.
  displayName: Source Image Name
  name: SOURCE_IMAGE_NAME
  value: 'nodejs'
  required: true
- description: The tag of the source image.
  displayName: Source Image Tag
  name: SOURCE_IMAGE_TAG
  value: "10"
  required: true
- description: SOURCE_REPOSITORY_URL
  displayName: SOURCE_REPOSITORY_URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/bcgov/realm-o-matic.git
- description: SOURCE_REPOSITORY_REF
  displayName: SOURCE_REPOSITORY_REF
  name: SOURCE_REPOSITORY_REF
  required: true
  value: master
- description: SOURCE_CONTEXT_DIR
  displayName: SOURCE_CONTEXT_DIR
  name: SOURCE_CONTEXT_DIR
  required: true
  value: web
  