apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    CONFIRMATION: ${CONFIRMATION}
    INVITATION: ${INVITATION}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: realmomatic-api-sso
  type: Opaque
parameters:
- description: SSO client secret for endpoints
  displayName: API_SSO_CLIENT_SECRET
  name: API_SSO_CLIENT_SECRET
  required: true
  value: ''
