apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    API_SSO_CLIENT_SECRET: ${API_SSO_CLIENT_SECRET}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: realmomatic-api-sso
    labels:
      app: realm-o-matic
  type: Opaque
parameters:
- description: SSO client secret for endpoints
  displayName: API_SSO_CLIENT_SECRET
  name: API_SSO_CLIENT_SECRET
  required: true
  value: ''
