apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  stringData:
    GITHUB_TOKEN: ${GITHUB_TOKEN}
    GITHUB_OWNER: ${GITHUB_OWNER}
    GITHUB_REPO: ${GITHUB_REPO}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: realmomatic-api-gh
  type: Opaque
parameters:
- description: Github account token
  displayName: GITHUB_TOKEN
  name: GITHUB_TOKEN
  required: true
  value: ''
- description: Github account token
  displayName: GITHUB_OWNER
  name: GITHUB_OWNER
  required: true
  value: ''
- description: Github account token
  displayName: GITHUB_REPO
  name: GITHUB_REPO
  required: true
  value: ''
