FROM node:10.10

RUN apt-get update && \
  yes | apt-get upgrade

RUN mkdir /home/app
WORKDIR /home/app

COPY package*.json /home/app/

RUN npm ci --silent
RUN npm i react-scripts --silent

COPY . .

EXPOSE 3000 9229
CMD [ "npm", "start" ] 
